# ejercicio2
print("segundos")
s = float(input())
print("minutos")
m = print(s/60.0)
print("horas")
h = print(s/3600)
print("segundos convertidos en segundos")
ss=print(s*1)
print("fin del de ejercicio")